{% set name = "pyxlsb" %}
{% set version = "1.0.10" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyxlsb-{{ version }}.tar.gz
  sha256: 8062d1ea8626d3f1980e8b1cfe91a4483747449242ecb61013bc2df85435f685

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  imports:
    - pyxlsb
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/wwwiiilll/pyxlsb
  summary: Excel 2007-2010 Binary Workbook (xlsb) parser
  license: LGPL-3.0-or-later
  license_file: COPYING

extra:
  recipe-maintainers:
    - cdesouza21
