{% set name = "pyxlsb" %}
{% set version = "1.0.10" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyxlsb-{{ version }}.tar.gz
  sha256: 8062d1ea8626d3f1980e8b1cfe91a4483747449242ecb61013bc2df85435f685

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vv

requirements:
  host:
    - pip
    - python
    - wheel
    - setuptools
  run:
    - python

test:
  imports:
    - pyxlsb
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/willtrnr/pyxlsb
  summary: Excel 2007+ Binary Workbook (xlsb) reader for Python
  description: pyxlsb is an Excel 2007-2010 Binary Workbook (xlsb) parser for Python. The library is currently extremely limited, but functional enough for basic data extraction.
  license: LGPL-3.0-or-later
  license_family: LGPL
  license_file: COPYING.LESSER
  doc_url: https://github.com/willtrnr/pyxlsb
  dev_url: https://github.com/willtrnr/pyxlsb

extra:
  recipe-maintainers:
    - cdesouza21
